I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/SceneScript/afterSubmission.rpy", line 192, in script
    return
Exception: Could not find return label ('game/SceneScript/afterSubmission.rpy', 1732234454, 1).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/SceneScript/afterSubmission.rpy", line 192, in script
    return
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\ast.py", line 1493, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "C:\Users\Jeevan\Desktop\Research of VN\RenPy Game\renpy-8.3.2-sdk\renpy\execution.py", line 744, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label ('game/SceneScript/afterSubmission.rpy', 1732234454, 1).

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
Path of The Function 1.0
Mon Jun  2 17:15:16 2025
